In [59]:
# Add the Pandas dependency.
import pandas as pd
import os


# Files to load
school_data_to_load = os.path.join("Resources", "schools_complete.csv")
student_data_to_load = os.path.join("Resources", "students_complete.csv")



# Read the school data file and store it in a Pandas DataFrame."read_csv" does this for us default.
school_data_df = pd.read_csv(school_data_to_load)
school_data_df


#To view first five lines of the dataframe 
school_data_df.head()

#To view first few lines of the dataframe specify the numer 
school_data_df.head(10)


#To view last few lines of the dataframe mention the lines
school_data_df.tail(10)


# Read the student data file and store it in a Pandas DataFrame.
student_data_df = pd.read_csv(student_data_to_load)
student_data_df.head()
student_data_df.tail()




# count() method, we can get a count of the rows for each column containing data. 
#By default, "null" values are not counted, so you can often quickly identify which columns have missing data.
#For school data frame 
school_data_df.count()

#For student dataframe
student_data_df.count()


#Determine if there are any missing values in the school data.
school_data_df.isnull()

student_data_df.isnull()


# Determine if there are not any missing values in the student data.
student_data_df.notnull().sum()


# Determine data types for the school DataFrame.
school_data_df.dtypes


school_data_df.budget.dtype

#find perticular column datatype
school_data_df.budget.dtype


school_data_df["budget"].dtype


# Determine data types for the student DataFrame.
student_data_df.dtypes


 

#To clean the Student name column by removing prefixes and suffixes
# Add each prefix and suffix to remove to a list.
prefixes_suffixes = ["Dr. ", "Mr. ","Ms. ", "Mrs. ", "Miss ", " MD", " DDS", " DVM", " PhD"]

# Iterate through the words in the "prefixes_suffixes" list and replace them with an empty space, "".
for word in prefixes_suffixes:
    student_data_df["student_name"] = student_data_df["student_name"].str.replace(word,"")
    
    
# Put the cleaned students' names in another list.
student_names = student_data_df["student_name"].tolist()
#student_names  

# Create a new list and use it for the for loop to iterate through the list.
students_fixed = []


# Use an if statement to check the length of the name.
# If the name is greater than or equal to 3, add the name to the list.


for name in student_names:
    if len(name.split()) >= 3:
        students_fixed.append(name)

# Get the length of the students' names that are greater than or equal to 3.
len(students_fixed)
    
 # Combine the data into a single dataset using merge()
school_data_complete_df = pd.merge(student_data_df, school_data_df, on=["school_name", "school_name"])
school_data_complete_df.head()

# Get the total number of students.
#student_count = (school_data_complete_df.count())--- will give full count so use column for accurate number
student_count=school_data_complete_df["Student ID"].count()

student_count

#alternative way to get the student count using student Id column
school_data_complete_df["Student ID"].count()

# Calculate the total number of schools.
school_count = school_data_df["school_name"].count()
school_count

# Calculate the total number of schools. unique() will return n dimentional array
school_count_2 = school_data_complete_df["school_name"].unique()
#use arrey len(arrey) function to get the lenth of the arrey that gives unique schools in this case
len(school_count_2)


# Calculate the total budget using school_data_df and not the completed merged data
total_budget = school_data_df["budget"].sum()
total_budget



# Calculate the average reading score.
average_reading_score = school_data_complete_df["reading_score"].mean()
average_reading_score


# Calculate the average math score.
average_math_score = school_data_complete_df["math_score"].mean()
average_math_score


#calculate the student passed in both subjects, this will return boolean value.
passing_math = school_data_complete_df["math_score"] >= 70
passing_reading = school_data_complete_df["reading_score"] >= 70

# Get all the students who are passing math in a new DataFrame.
passing_math = school_data_complete_df[school_data_complete_df["math_score"] >= 70]
passing_math.head()



# Get all the students that are passing reading in a new DataFrame.
passing_reading = school_data_complete_df[school_data_complete_df["reading_score"] >= 70]    
passing_reading.head()


#get the count of total passed  in math and than reading respectively.
passing_math_count = passing_math["student_name"].count()
passing_reading_count = passing_reading["student_name"].count()


# Calculate the percent that passed math.
passing_math_percentage = passing_math_count / (student_count) * 100


# Calculate the percent that passed reading.
passing_reading_percentage = passing_reading_count / student_count * 100

# Calculate the students who passed both math and reading.
passing_math_reading = school_data_complete_df[(school_data_complete_df["math_score"] >= 70) & (school_data_complete_df["reading_score"] >= 70)]

passing_math_reading.head()

#passing_math_reading["student_name"].count()


# Calculate the number of students who passed both math and reading.
overall_passing_math_reading_count = passing_math_reading["student_name"].count()
#another way is 
#passing_math_reading.student_name.count()
overall_passing_math_reading_count


# Calculate the overall passing percentage.
overall_passing_percentage = overall_passing_math_reading_count / student_count * 100
overall_passing_percentage




# Adding a list of values with keys to create a new DataFrame.
district_summary_df = pd.DataFrame(
          [{"Total Schools": school_count,
          "Total Students": student_count,
          "Total Budget": total_budget,
          "Average Math Score": average_math_score,
          "Average Reading Score": average_reading_score,
          "% Passing Math": passing_math_percentage,
         "% Passing Reading": passing_reading_percentage,
        "% Overall Passing": overall_passing_percentage}])
district_summary_df


# Format the "Total Students" to have the comma for a thousands separator.
district_summary_df["Total Students"] = district_summary_df["Total Students"].map("{:,}".format)

print(district_summary_df["Total Students"])


# Format "Total Budget" to have the comma for a thousands separator, a decimal separator, and a "$".

district_summary_df["Total Budget"] = district_summary_df["Total Budget"].map("${:,.2f}".format)

district_summary_df["Total Budget"]


# Format the columns.
district_summary_df["Average Math Score"] = district_summary_df["Average Math Score"].map("{:.1f}".format)

district_summary_df["Average Reading Score"] = district_summary_df["Average Reading Score"].map("{:.1f}".format)

district_summary_df["% Passing Math"] = district_summary_df["% Passing Math"].map("{:.0f}".format)

district_summary_df["% Passing Reading"] = district_summary_df["% Passing Reading"].map("{:.0f}".format)

district_summary_df["% Overall Passing"] = district_summary_df["% Overall Passing"].map("{:.0f}".format)



# Reorder the columns in the order you want them to appear.
new_column_order = ["Total Schools", "Total Students", "Total Budget","Average Math Score", "Average Reading Score", "% Passing Math", "% Passing Reading", "% Overall Passing"]

# Assign district summary df the new column order.
district_summary_df = district_summary_df[new_column_order]
district_summary_df

E:\anacondaFiles\envs\PythonData\lib\site-packages\ipykernel_launcher.py:80: FutureWarning: The default value of regex will change from True to False in a future version.

0    39,170
Name: Total Students, dtype: object

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
0,15,"39,170","$24,649,428.00",79.0,81.9,75,86,65